all:
	g++ ascii_compress.cpp tree_node.cpp -o ascii_compress

	g++ ascii_decompress.cpp tree_node.cpp -o ascii_decompress

	g++ decompress.cpp tree_node.cpp -o decompress

	g++ compress.cpp tree_node.cpp -o compress